buildscript {
    ext.kotlin_version = '2.1.0'  // Updated for better compatibility
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        // Android Gradle Plugin version is now managed in settings.gradle
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}